os:
  editPreset: "nvim"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  showFileTree: false

customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
